# Generated by Django 2.0.2 on 2018-03-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Data', models.CharField(max_length=250)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
